package sybrix.easygsp2.http

import javax.activation.MimeType


class MimeTypes {
        static Map<String, MimeType> mimeTypes= [
        ".aac": new MimeType("audio/aac"),
        ".abw": new MimeType("application/x-abiword"),
        ".arc": new MimeType("application/x-freearc"),
        ".avi": new MimeType("video/x-msvideo"),
        ".azw": new MimeType("application/vnd.amazon.ebook"),
        ".bin": new MimeType("application/octet-stream"),
        ".bmp": new MimeType("image/bmp"),
        ".bz": new MimeType("application/x-bzip"),
        ".bz2": new MimeType("application/x-bzip2"),
        ".csh": new MimeType("application/x-csh"),
        ".css": new MimeType("text/css"),
        ".csv": new MimeType("text/csv"),
        ".doc": new MimeType("application/msword"),
        ".docx": new MimeType("application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
        ".eot": new MimeType("application/vnd.ms-fontobject"),
        ".epub": new MimeType("application/epub+zip"),
        ".gif": new MimeType("image/gif"),
        ".htm": new MimeType("text/html"),
        ".html": new MimeType("text/html"),
        ".ico": new MimeType("image/vnd.microsoft.icon"),
        ".ics": new MimeType("text/calendar"),
        ".jar": new MimeType("application/java-archive"),
        ".jpeg": new MimeType("image/jpeg"),
        ".jpg": new MimeType("image/jpeg"),
        ".json": new MimeType("application/json"),
        ".jsonld": new MimeType("application/ld+json"),
        ".mid": new MimeType("audio/midi"),
        ".midi": new MimeType("audio/midi"),
        ".mjs": new MimeType("text/javascript"),
        ".mp3": new MimeType("audio/mpeg"),
        ".mpeg": new MimeType("video/mpeg"),
        ".mpkg": new MimeType("application/vnd.apple.installer+xml"),
        ".odp": new MimeType("application/vnd.oasis.opendocument.presentation"),
        ".ods": new MimeType("application/vnd.oasis.opendocument.spreadsheet"),
        ".odt": new MimeType("application/vnd.oasis.opendocument.text"),
        ".oga": new MimeType("audio/ogg"),
        ".ogv": new MimeType("video/ogg"),
        ".ogx": new MimeType("application/ogg"),
        ".otf": new MimeType("font/otf"),
        ".png": new MimeType("image/png"),
        ".pdf": new MimeType("application/pdf"),
        ".ppt": new MimeType("application/vnd.ms-powerpoint"),
        ".pptx": new MimeType("application/vnd.openxmlformats-officedocument.presentationml.presentation"),
        ".rar": new MimeType("application/x-rar-compressed"),
        ".rtf": new MimeType("application/rtf"),
        ".sh": new MimeType("application/x-sh"),
        ".svg": new MimeType("image/svg+xml"),
        ".swf": new MimeType("application/x-shockwave-flash"),
        ".tar": new MimeType("application/x-tar"),
        ".tif": new MimeType("image/tiff"),
        ".tiff": new MimeType("image/tiff"),
        ".ttf": new MimeType("font/ttf"),
        ".txt": new MimeType("text/plain"),
        ".vsd": new MimeType("application/vnd.visio"),
        ".wav": new MimeType("audio/wav"),
        ".weba": new MimeType("audio/webm"),
        ".webm": new MimeType("video/webm"),
        ".webp": new MimeType("image/webp"),
        ".woff": new MimeType("font/woff"),
        ".woff2": new MimeType("font/woff2"),
        ".xhtml": new MimeType("application/xhtml+xml"),
        ".xls": new MimeType("application/vnd.ms-excel"),
        ".xlsx": new MimeType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
        ".xml": new MimeType("application/xml"),
        ".xul": new MimeType("application/vnd.mozilla.xul+xml"),
        ".zip": new MimeType("application/zip"),
        ".7z": new MimeType("application/x-7z-compressed")]
}
